// vue/src/Deck.vue
<script setup lang="ts">
import {
	ref,
	watch,
	onMounted,
	onUnmounted,
	provide,
	shallowRef,
	useAttrs,
	useTemplateRef,
	computed,
} from 'vue';
import Reveal, { type RevealApi } from 'reveal.js';
import type { DeckProps, DeckEmits } from './types';
import { RevealContextKey } from './context';

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<DeckProps>(), {
	plugins: () => [],
});

const emit = defineEmits<DeckEmits>();
const attrs = useAttrs();

const revealClasses = computed(() => {
	const base = 'reveal';
	const extra = attrs.class;
	if (!extra) return base;
	if (typeof extra === 'string') return `${base} ${extra}`;
	if (Array.isArray(extra)) return [base, ...extra];
	return [base, extra];
});

const deckDivRef = useTemplateRef<HTMLDivElement>('deckEl');
const slidesDivRef = useTemplateRef<HTMLDivElement>('slidesEl');
const revealRef = shallowRef<RevealApi | null>(null);
const isReady = ref(false);

const initialPlugins = [...props.plugins];
const skipNextSyncCount = ref(0);

const slideIds = new WeakMap<HTMLElement, number>();
let nextSlideId = 1;
let lastSyncedSlidesSignature: string | null = null;
let currentConfig = { ...props.config };
let observer: MutationObserver | null = null;
let boundEventHandlers: Array<{ name: string; handler: (e: any) => void }> = [];

provide(RevealContextKey, revealRef);

defineExpose({
	reveal: revealRef,
});

function hasShallowConfigChanges(prev: DeckProps['config'], next: DeckProps['config']) {
	if (prev === next) return false;
	if (!prev || !next) return prev !== next;

	const prevKeys = Object.keys(prev);
	const nextKeys = Object.keys(next);

	if (prevKeys.length !== nextKeys.length) return true;

	for (const key of prevKeys) {
		if (!(key in next)) return true;
		if ((prev as Record<string, unknown>)[key] !== (next as Record<string, unknown>)[key]) {
			return true;
		}
	}

	return false;
}

function isSectionElement(element: Element): element is HTMLElement {
	return element.tagName === 'SECTION';
}

function getSectionStructure(
	container: Element,
	slideIdsMap: WeakMap<HTMLElement, number>
): (number | [number, any])[] {
	return Array.from(container.children)
		.filter(isSectionElement)
		.map((section) => {
			let id = slideIdsMap.get(section);
			if (id === undefined) {
				id = nextSlideId++;
				slideIdsMap.set(section, id);
			}

			const childSlides = getSectionStructure(section, slideIdsMap);
			return childSlides.length > 0 ? [id, childSlides] : id;
		});
}

function getSlidesStructureSignature(
	slidesElement: HTMLElement | null,
	slideIdsMap: WeakMap<HTMLElement, number>
) {
	if (!slidesElement) return '[]';
	return JSON.stringify(getSectionStructure(slidesElement, slideIdsMap));
}

function wireEvents(deck: RevealApi) {
	const events: [string, string][] = [
		['sync', 'sync'],
		['slidesync', 'slideSync'],
		['slidechanged', 'slideChanged'],
		['slidetransitionend', 'slideTransitionEnd'],
		['fragmentshown', 'fragmentShown'],
		['fragmenthidden', 'fragmentHidden'],
		['overviewshown', 'overviewShown'],
		['overviewhidden', 'overviewHidden'],
		['paused', 'paused'],
		['resumed', 'resumed'],
	];

	for (const [name, emitName] of events) {
		const handler = (e: any) => (emit as any)(emitName, e);
		deck.on(name, handler);
		boundEventHandlers.push({ name, handler });
	}
}

function unwireEvents(deck: RevealApi) {
	for (const { name, handler } of boundEventHandlers) {
		deck.off(name, handler);
	}
	boundEventHandlers = [];
}

onMounted(() => {
	if (!deckDivRef.value) return;

	const instance = new Reveal(deckDivRef.value, {
		...props.config,
		plugins: initialPlugins,
	});

	revealRef.value = instance;

	instance.initialize().then(() => {
		if (revealRef.value !== instance) return;
		lastSyncedSlidesSignature = getSlidesStructureSignature(slidesDivRef.value, slideIds);
		isReady.value = true;
		wireEvents(instance);
		emit('ready', instance);
	});

	observer = new MutationObserver(() => {
		const shouldSkip = skipNextSyncCount.value > 0;
		if (shouldSkip) {
			skipNextSyncCount.value--;
		}

		const signature = getSlidesStructureSignature(slidesDivRef.value, slideIds);

		if (shouldSkip) {
			lastSyncedSlidesSignature = signature;
			return;
		}

		if (!isReady.value || !revealRef.value) return;
		if (lastSyncedSlidesSignature === signature) return;

		revealRef.value.sync();
		lastSyncedSlidesSignature = signature;
	});

	if (slidesDivRef.value) {
		observer.observe(slidesDivRef.value, { childList: true, subtree: true });
	}
});

onUnmounted(() => {
	const instance = revealRef.value;
	if (observer) {
		observer.disconnect();
	}

	if (!instance) return;

	unwireEvents(instance);

	try {
		instance.destroy();
	} catch (e) {
		// Ignore errors during cleanup
	}

	if (revealRef.value === instance) {
		revealRef.value = null;
		isReady.value = false;
	}
});

watch(
	() => props.config,
	(newConfig) => {
		if (!isReady.value || !revealRef.value) return;
		if (!hasShallowConfigChanges(currentConfig, newConfig)) return;

		skipNextSyncCount.value++;
		revealRef.value.configure(newConfig ?? {});
		currentConfig = { ...newConfig };
	},
	{ deep: false }
);
</script>

<template>
	<div :class="revealClasses" :style="(attrs.style as any)" ref="deckEl">
		<div class="slides" ref="slidesEl">
			<slot />
		</div>
	</div>
</template>

// react/src/Deck.tsx
import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import Reveal from 'reveal.js';
import { RevealContext } from './context';
import type { DeckProps } from './types';

function setRef<T>(ref: React.Ref<T | null> | undefined, value: T | null) {
	if (!ref) return;
	if (typeof ref === 'function') {
		ref(value);
	} else if (typeof ref === 'object') {
		(ref as { current: T | null }).current = value;
	}
}

export function Deck(props: DeckProps) {
	const {
		plugins,
		onReady,
		onSync,
		onSlideChange,
		onSlideTransitionEnd,
		onFragmentShown,
		onFragmentHidden,
		onOverviewShown,
		onOverviewHidden,
		onPaused,
		onResumed,
		deckRef,
		className,
		style,
		children,
		...revealOptions
	} = props;

	const deckDivRef = useRef<HTMLDivElement>(null);
	const revealRef = useRef<Reveal.Api | null>(null);
	const [deck, setDeck] = useState<Reveal.Api | null>(null);

	useEffect(() => {
		if (revealRef.current) return;

		let mounted = true;

		const instance = new Reveal(deckDivRef.current!, {
			...revealOptions,
			plugins: plugins ?? [],
		});
		revealRef.current = instance;

		instance.initialize().then(() => {
			if (!mounted) return;
			setDeck(instance);
			setRef(deckRef, instance);
			onReady?.(instance);
		});

		return () => {
			mounted = false;
			try {
				instance.destroy();
			} catch (e) {
				// Ignore errors during cleanup
			}
			revealRef.current = null;
			setDeck(null);
			setRef(deckRef, null);
		};
	}, []); // eslint-disable-line react-hooks/exhaustive-deps

	useEffect(() => {
		if (!deck) return;

		const events: [string, ((e: any) => void) | undefined][] = [
			['sync', onSync],
			['slidechanged', onSlideChange],
			['slidetransitionend', onSlideTransitionEnd],
			['fragmentshown', onFragmentShown],
			['fragmenthidden', onFragmentHidden],
			['overviewshown', onOverviewShown],
			['overviewhidden', onOverviewHidden],
			['paused', onPaused],
			['resumed', onResumed],
		];

		const bound: [string, (e: any) => void][] = [];
		for (const [name, handler] of events) {
			if (handler) {
				deck.on(name, handler);
				bound.push([name, handler]);
			}
		}

		return () => {
			for (const [name, handler] of bound) {
				deck.off(name, handler);
			}
		};
	}, [
		deck,
		onSlideChange,
		onSlideTransitionEnd,
		onFragmentShown,
		onFragmentHidden,
		onOverviewShown,
		onOverviewHidden,
		onPaused,
		onResumed,
	]);

	useEffect(() => {
		if (!deck) return;
		deck.configure({
			...revealOptions,
			plugins: plugins ?? [],
		});
	}, [deck, revealOptions, plugins]);

	useLayoutEffect(() => {
		if (revealRef.current?.isReady()) {
			revealRef.current.sync();
		}
	});

	return (
		<RevealContext.Provider value={deck}>
			<div className={className ? `reveal ${className}` : 'reveal'} style={style} ref={deckDivRef}>
				<div className="slides">{children}</div>
			</div>
		</RevealContext.Provider>
	);
}
