// vue/src/components/Slide.vue
<script setup lang="ts">
import { computed, inject, shallowRef, useTemplateRef, watch, useAttrs } from 'vue';
import type { RevealApi } from 'reveal.js';
import type { SlideProps } from '../types';
import { RevealContextKey } from '../reveal-context';
import {
	EMPTY_DATA_ATTRIBUTES_SIGNATURE,
	getDataAttributesSignature,
	getSlideAttributes,
} from '../utils/slide-attributes';

defineOptions({ inheritAttrs: false });

const props = defineProps<SlideProps>();
const attrs = useAttrs();

const deckRef = inject(RevealContextKey, shallowRef<RevealApi | null>(null));
const slideRef = useTemplateRef<HTMLElement>('slideEl');

const lastSyncedDeckRef = shallowRef<RevealApi | null>(null);
const lastSyncedSignatureRef = shallowRef<string | null>(null);

const slideAttributes = computed(() => {
	return getSlideAttributes(attrs, props);
});

const dataAttributesSignature = computed(() => {
	return getDataAttributesSignature(slideAttributes.value);
});

watch([deckRef, dataAttributesSignature, slideRef], ([deck, signature, slide]) => {
	if (!deck || !slide || typeof deck.syncSlide !== 'function') return;

	// The first render for a given deck instance is handled by the parent Deck.sync() pass.
	// syncSlide() is only safe once Reveal is aware of this slide.
	if (!lastSyncedDeckRef.value || lastSyncedDeckRef.value !== deck) {
		lastSyncedDeckRef.value = deck;
		lastSyncedSignatureRef.value = signature;
		return;
	}

	if (signature === EMPTY_DATA_ATTRIBUTES_SIGNATURE) return;

	const sameDeck = lastSyncedDeckRef.value === deck;
	const sameDataAttributes = lastSyncedSignatureRef.value === signature;
	if (sameDeck && sameDataAttributes) return;

	deck.syncSlide(slide);
	lastSyncedDeckRef.value = deck;
	lastSyncedSignatureRef.value = signature;
}, { immediate: true });
</script>

<template>
	<section ref="slideEl" v-bind="slideAttributes">
		<slot />
	</section>
</template>

// react/src/Slide.tsx
import { useContext, useLayoutEffect, useMemo, useRef } from 'react';
import type { RevealApi } from 'reveal.js';
import { RevealContext } from './context';
import type { SlideProps } from './types';

const EMPTY_DATA_ATTRIBUTES_SIGNATURE = '[]';

function getDataAttributesSignature(attributes: Omit<SlideProps, 'children'>) {
	return JSON.stringify(
		Object.entries(attributes)
			.filter(([key]) => key.startsWith('data-'))
			.sort(([a], [b]) => a.localeCompare(b))
	);
}

export function Slide({ children, ...rest }: SlideProps) {
	const deck = useContext(RevealContext);
	const slideRef = useRef<HTMLElement>(null);
	const lastSyncedDeckRef = useRef<RevealApi | null>(null);
	const lastSyncedSignatureRef = useRef<string | null>(null);
	const dataAttributesSignature = useMemo(() => getDataAttributesSignature(rest), [rest]);

	useLayoutEffect(() => {
		const slide = slideRef.current;
		if (!deck || !slide || typeof deck.syncSlide !== 'function') return;

		// The first render for a given deck instance is handled by the parent Deck.sync() pass.
		// syncSlide() is only safe once Reveal is aware of this slide.
		if (lastSyncedDeckRef.current !== deck) {
			lastSyncedDeckRef.current = deck;
			lastSyncedSignatureRef.current = dataAttributesSignature;
			return;
		}

		if (dataAttributesSignature === EMPTY_DATA_ATTRIBUTES_SIGNATURE) return;

		const sameDeck = lastSyncedDeckRef.current === deck;
		const sameDataAttributes = lastSyncedSignatureRef.current === dataAttributesSignature;
		if (sameDeck && sameDataAttributes) return;

		deck.syncSlide(slide);
		lastSyncedDeckRef.current = deck;
		lastSyncedSignatureRef.current = dataAttributesSignature;
	}, [deck, dataAttributesSignature]);

	return (
		<section ref={slideRef} {...rest}>
			{children}
		</section>
	);
}
