// react/src/Fragment.tsx
import type { FragmentProps } from './types';

export function Fragment({
	animation,
	index,
	as: Tag = 'span',
	className,
	style,
	children,
}: FragmentProps) {
	const classes = ['fragment', animation, className].filter(Boolean).join(' ');

	return (
		<Tag className={classes} style={style} data-fragment-index={index}>
			{children}
		</Tag>
	);
}

// vue/src/Fragment.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { FragmentProps } from './types';

const props = withDefaults(defineProps<FragmentProps>(), {
	as: 'span',
});

const classes = computed(() => {
	return ['fragment', props.animation].filter(Boolean).join(' ');
});
</script>

<template>
	<component :is="as" :class="classes" :data-fragment-index="index">
		<slot />
	</component>
</template>
