// vue/src/components/Fragment.vue
<script setup lang="ts">
import { computed, useSlots, h, cloneVNode } from 'vue';
import type { FragmentProps } from '../types';

const props = defineProps<FragmentProps>();
const slots = useSlots();

const classes = computed(() => {
	const base = ['fragment', props.animation];
	if (props.class) base.push(props.class);
	return base.filter(Boolean);
});

// Since we are using render function logic for asChild, we define a small render component
function renderContent() {
	if (props.asChild) {
		const children = slots.default?.();
		if (!children || children.length !== 1) {
			throw new Error('Fragment with asChild expects exactly one child.');
		}
		const child = children[0];
		return cloneVNode(child, {
			class: [child.props?.class, classes.value],
			style: [child.props?.style, props.style],
			'data-fragment-index': props.index,
		});
	}

	const Tag = props.as ?? 'span';
	return h(
		Tag,
		{
			class: classes.value,
			style: props.style,
			'data-fragment-index': props.index,
		},
		slots.default?.()
	);
}
</script>

<template>
	<component :is="renderContent" />
</template>

// react/src/components/fragment.tsx
import {
	Children,
	Fragment as ReactFragment,
	cloneElement,
	isValidElement,
	type CSSProperties,
	type ReactElement,
} from 'react';
import type { FragmentProps } from '../types';

type FragmentChildProps = {
	className?: string;
	style?: CSSProperties;
	'data-fragment-index'?: number;
};

function mergeClassNames(...classNames: Array<string | undefined>) {
	return classNames.filter(Boolean).join(' ');
}

function mergeStyles(
	childStyle: CSSProperties | undefined,
	style: CSSProperties | undefined
) {
	if (!childStyle) return style;
	if (!style) return childStyle;

	return {
		...childStyle,
		...style,
	};
}

export function Fragment({
	animation,
	index,
	as,
	asChild,
	className,
	style,
	children,
}: FragmentProps) {
	const classes = mergeClassNames('fragment', animation, className);

	if (asChild) {
		let child: ReactElement<FragmentChildProps>;
		try {
			child = Children.only(children) as ReactElement<FragmentChildProps>;
		} catch {
			throw new Error('Fragment with asChild expects exactly one React element child.');
		}

		if (!isValidElement(child) || child.type === ReactFragment) {
			throw new Error('Fragment with asChild expects exactly one non-Fragment React element child.');
		}

		const fragmentChildProps: FragmentChildProps = {
			className: mergeClassNames(child.props.className, classes),
			style: mergeStyles(child.props.style, style),
		};

		if (index !== undefined) {
			fragmentChildProps['data-fragment-index'] = index;
		}

		return cloneElement(child, fragmentChildProps);
	}

	const Tag = as ?? 'span';

	return (
		<Tag className={classes} style={style} data-fragment-index={index}>
			{children}
		</Tag>
	);
}
